apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-pv-claim
  labels: 
    app: wordpress_db
spec: 
  accessModes: 
  - ReadWriteMany
  resources: 
    requests: 
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-svc
  labels: 
    app: wordpress_db
spec: 
  ports: 
  - port: 3306
  selector: 
    app: wordpress_db
    tier: mysq
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: wordpress_db
  name: mysql-deployment
spec: 
  selector: 
    matchLabels: 
      app: wordpress_db
      tier: mysql
  strategy: 
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: wordpress_db
        tier: mysql
    spec: 
      containers: 
      - image: mysql_img
        imagePullPolicy: Never
        name: mysql
        ports: 
        - containerPort: 3306
        volumeMounts: 
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes: 
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
