apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
spec: 
  ports: 
    - 
      name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - 
      name: https
      port: 443
      protocol: TCP
      targetPort: 443
    -
      name: ssh
      port: 22
      targetPort: 22
  selector: 
    app: nginx
  loadBalancerIP: 192.168.99.102
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx_img
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22