apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
	app: wordpress
spec:
  ports:
	- port: 5050
  selector:
	app: wordpress
  loadBalancerIP: 192.168.99.103
  type: LoadBalancer
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wp-pviclaim
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
	app: wordpress
spec:
  replicas: 1
  selector:
	matchLabels:
	  app: wordpress
  template:
	metadata:
	  labels:
		app: wordpress
	spec:
	  containers:
	  - name: wordpress
		image: wp_img
		imagePullPolicy: Never
		# env:
		# - name: WORDPRESS_DB_HOST
		#   value: wordpress-mysql
		# - name: WORDPRESS_DB_PASSWORD
		#   valueFrom:
		#     secretKeyRef:
		#       name: mysql-pass
		#       key: password
		ports:
		- containerPort: 5050
	  #     name: wordpress
	  #   volumeMounts:
	  #   - name: wordpress-persistent-storage
	  #     mountPath: /var/www/localhost
	  # volumes:
	  # - name: wordpress-persistent-storage
	  #   persistentVolumeClaim:
	  #     claimName: wp-pv-claim